services:
  # install gateway in host machine
  # for debian system, we use `apt install nginx -y`
  # gateway:
  #  image: nginx:1.29-bookworm
  #  container_name: gateway
  #  restart: unless-stopped
  #  volumes:
  #    - ./nginx/:/etc/nginx/conf.d/
  #    - ./html:/usr/share/nginx/html
  #    - ./log/nginx/:/var/log/nginx/
  #  ports:
  #    - "80:80"
  crproxy:
    image: ghcr.io/daocloud/crproxy/crproxy:v0.12.4
    container_name: crproxy
    restart: unless-stopped
    # ports:
    # - 80:8080
    # - 443:8080
    ports:
      - "8080:8080"
    # 由于acme需要一个临时目录来存储证书，这里使用tmpfs来加速
    command: |
      --acme-cache-dir=/tmp/acme
      --acme-hosts=*
      --default-registry=docker.io
    tmpfs:
      - /tmp/acme
    # 非必须, 如果这台服务器无法畅通的达到你要的镜像仓库可以尝试配置
    # environment:
    #  - https_proxy=http://proxy:8080
    #  - http_proxy=http://proxy:8080